<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\MasterTraining;

class MasterTrainingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
{
$trainings = [
    'AK3U Kemnaker',
    'Auditor SMK3 Kemnaker',
    'Ahli K3 Spesialis PAA Kemnaker',
    'Ahli K3 Spesialis PTP (Pesawat Tenaga Produksi) Kemnaker',
    'Ahli K3 Spesialis PUBT (Pesawat Uap & Bejana Tekan) Kemnaker',
    'Teknisi/Petugas Pemeriksa Penguji PAA Kemnaker',
    'Teknisi/Petugas Pemeriksa Penguji PTP Kemnaker',
    'Teknisi/Petugas Pemeriksa Penguji PU (Pesawat Uap) Kemnaker',
    'Teknisi/Petugas Pemeriksa Penguji BT3 (Bejana Tekan & Tangki Timbun) Kemnaker',
    'Operator Crane Overhead Kelas 1 Kemnaker',
    'Operator Crane Overhead Kelas 2 Kemnaker',
    'Operator Crane Overhead Kelas 3 Kemnaker',
    'Operator Crane Mobile Kelas 1 Kemnaker',
    'Operator Crane Mobile Kelas 2 Kemnaker',
    'Operator Crane Mobile Kelas 3 Kemnaker',
    'Operator Crane Tower Kelas 1 Kemnaker',
    'Operator Crane Tower Kelas 2 Kemnaker',
    'Operator Crane Tower Kelas 3 Kemnaker',
    'Juru Ikat (Rigger) Kemnaker',
    'Operator Gondola, Dongkrak Mekanik, Takel, dan Mesin Pancang Kemnaker',
    'Operator Pita Transport (Conveyor Belt) Kemnaker',
    'Operator Angkutan jalan Rel Kemnaker',
    'Operator Alat Berat Loader Kemnaker',
    'Operator Alat Berat Buldozer Kemnaker',
    'Operator Alat Berat Excavator Kemnaker',
    'Operator Alat Berat Unloader Kemnaker',
    'Operator Alat Berat Dump Truck Kemnaker',
    'Operator Alat Berat Boom Truck Kemnaker',
    'Operator Alat Berat Mixer Truck Kemnaker',
    'Operator Alat Berat Trailer Kemnaker',
    'Operator Forklift Kelas 1 Kemnaker',
    'Operator Forklift Kelas 2 Kemnaker',
    'Operator Penggerak Mula Kelas 1 Kemnaker',
    'Operator Penggerak Mula Kelas 2 Kemnaker',
    'Operator Mesin Produksi & Perkakas Kelas 1 (Alat Automatic) Kemnaker',
    'Operator Mesin Produksi & Perkakas Kelas 2 (Alat Manual) Kemnaker',
    'Operator Tanur Kelas 1 Kemnaker',
    'Operator Tanur Kelas 2 Kemnaker',
    'Operator Pesawat Uap & Bejana Tekan (Boiler) Kelas 1 Kemnaker',
    'Operator Pesawat Uap & Bejana Tekan (Boiler) Kelas 2 Kemnaker',
    'Juru Las GTAW/Argon Bahan CS Kelas 1 Kemnaker',
    'Juru Las GTAW/Argon Bahan CS Kelas 2 Kemnaker',
    'Juru Las GTAW/Argon Bahan CS Kelas 3 Kemnaker',
    'Juru Las GTAW/Argon Bahan SS Kelas 1 Kemnaker',
    'Juru Las GTAW/Argon Bahan SS Kelas 2 Kemnaker',
    'Juru Las GTAW/Argon Bahan SS Kelas 3 Kemnaker',
    'Juru Las GTAW/Argon Bahan CS SS Kelas 1 Kemnaker',
    'Juru Las GTAW/Argon Bahan CS SS Kelas 2 Kemnaker',
    'Juru Las GTAW/Argon Bahan CS SS Kelas 3 Kemnaker',
    'Juru Las SMAW/Listrik Kelas 1 Kemnaker',
    'Juru Las SMAW/Listrik Kelas 2 Kemnaker',
    'Juru Las SMAW/Listrik Kelas 3 Kemnaker',
    'Juru Las GMAW/CO2 Kelas 1 Kemnaker',
    'Juru Las GMAW/CO2 Kelas 2 Kemnaker',
    'Juru Las GMAW/CO2 kelas 3 Kemnaker',
    'Juru Las FCAW Kelas 1 Kemnaker',
    'Juru Las FCAW Kelas 2 Kemnaker',
    'Juru Las FCAW Kelas 3 Kemnaker',
    'Juru Las FCAW+GMAW KELAS 1 Bahan CS Kemnaker',
    'Juru Las OAW/Karbit Kemnaker',
    'Juru Las GTAW+SMAW Bahan CS kelas 1 Kemnaker',
    'Juru Las GTAW+SMAW Bahan CS kelas 2 Kemnaker',
    'Juru Las GTAW+SMAW Bahan CS Kelas 3 Kemnaker',
    'Juru Las GTAW+SMAW Bahan SS Kelas 1 Kemnaker',
    'Juru Las GTAW+SMAW Bahan SS Kelas 2 Kemnaker',
    'Juru Las GTAW+SMAW Bahan SS Kelas 3 Kemnaker',
    'Juru Las GMAW+SMAW kelas 1 Kemnaker',
    'Juru Las GMAW+SMAW kelas 2 Kemnaker',
    'Juru Las GMAW+SMAW kelas 3 Kemnaker',
    'Ahli K3 Spesialis Listrik Kemnaker',
    'Teknisi K3 Listrik Kemnaker',
    'Ahli K3 Spesialis Kebakaran Kelas A Kemnaker',
    'K3 Kebakaran Kelas B Kemnaker',
    'K3 Kebakaran kelas C Kemnaker',
    'K3 Kebakaran Kelas D Kemnaker',
    'K3 Kebakaran DCBA Kemnaker',
    'K3 Kebakaran DCB Kemnaker',
    'K3 Kebakaran BA Kemnaker',
    'K3 Kebakaran DC Kemnaker',
    'Ahli K3 Spesilais Elevator dan Eskalator Kemnaker',
    'Teknisi K3 Elevator dan Eskalator Kemnaker',
    'Operator K3 Elevator dan Eskalator Kemnaker',
    'Ahli Muda K3 Konstruksi Kemnaker',
    'Ahli Madya K3 Konstruksi Kemnaker',
    'Ahli Utama k3 Konstruksi Kemnaker',
    'Teknisi K3 Perancah Kemnaker',
    'Supervisi K3 Perancah Kemnaker',
    'Hyperkes Untuk Paramedis Kemnaker',
    'Hyperkes Untuk Dokter Kemnaker',
    'Petugas P3K Kemnaker',
    'Petugas K3 Asbes Kemnaker',
    'Teknisi K3 Pestisida Kemnaker',
    'Teknisi K3 Deteksi Gas Kemnaker',
    'Petugas K3 Utama Ruang Terbatas (Confined Space) Kemnaker',
    'Petugas K3 Madya Ruang Terbatas (Confined Space) Kemnaker',
    'Petugas K3 Penyelamat (Rescuer) Ruang Terbatas Kemnaker',
    'Ahli K3 Kimia Kemnaker',
    'Petugas K3 Kimia Kemnaker',
    'Ahli K3 Muda Lingkungan kerja/Lingker Kemnaker',
    'Ahli K3 Madya Lingkungan Kerja/Lingker Kemnaker',
    'Ahli K3 Utama Lingkungan Kerja/Lingker Kemnaker',
    'TKBT Tingkat 1 Kemnaker',
    'TKBT Tingkat 2 Kemnaker',
    'TKPK Tingkat 1 Kemnaker',
    'TKPK Tingkat 2 Kemnaker',
    'TKPK Tingkat 3 Kemnaker',
    'AK3U BNSP',
    'HR STAFF BNSP',
    'HR SUPERVISOR BNSP',
    'HR MANAGER BNSP',
    'PPPA BNSP',
    'POPAL BNSP',
    'PLB3 BNSP',
    'PLNB3 BNSP',
    'OPLB3 BNSP',
    'OPLNB3 BNSP',
    'MPLB3 BNSP',
    'PPPU BNSP',
    'POIPU BNSP',
    'PCUA BNSP',
    'First Aid BNSP',
    'P3K BNSP',
    'Keahlian Penghitungan Nilai Daur Hidup (LCA) BNSP',
    'Pengambilan Data Penilai Daur Hidup (LCA) BNSP',
    'Pengawas Pemilah Sampah BNSP',
    'Pemilah Sampah BNSP',
    'Penjaminan Keamanan Pangan Segar Asal Tumbuhan BNSP',
    'Pengelolaan Hyghine Sanitasi Makanan BNSP',
    'Inspeksi Hyghine Sanitasi Makanan BNSP',
    'Pengelolaan Cara Produksi Pangan Olahan yang Baik (CPPOB) BNSP',
    'Inspeksi Cara Produksi Pangan Olahan yang Baik (CPPOB) BNSP',
    'Penyusunan Dokumen System HACCP BNSP',
    'Audit Eksternal Keamanan Pangan BNSP',
    'Pengelolaan Keamanan Pangan Berbasis Haccp BNSP',
    'Konsultasi Keamanan Pangan BNSP',
    'Pengelolaan Cara Ritel Pangan Yang Baik BNSP',
    'Inspeksi Cara Ritel Pangan Yang Baik BNSP',
    'Audit Internal Provisi Keamanan Pangan BNSP',
    'Okupasi Nasional Penjamah Makanan (Food Handler) BNSP',
    'Audit Internal Keamanan Pangan BNSP',
    'Pengawas Smk3 Kontraktor (CSMS) BNSP',
    'Safetyman Migas BNSP',
    'Safetyman Umum BNSP',
    'Ahli Hazops BNSP',
    'Ahli Investigasi Insiden BNSP',
    'Petugas Fasilitas K3 Kesehatan BNSP',
    'Safety Inspektor BNSP',
    'Petugas Penanganan Bahaya Gas H2S BNSP',
    'Ahli Kajian Resiko Kesehatan Kerja BNSP',
    'Operator Gas Tester BNSP',
    'Pelaksanaan Investigasi Kecelakaan Tambang BNSP',
    'Pelaksanaan Inspeksi K3 Pertambangan BNSP',
    'Penyusunan Ibpr Pertambangan BNSP',
    'Penyusunan Jsa Pertambangan BNSP',
    'Supervisor Environment BNSP',
    'POP BNSP',
    'POM BNSP',
    'POU BNSP',
    'Petugas Pengambil Contoh Uji Laboratorium BNSP',
    'Petugas Pengambil Contoh Uji Air BNSP',
    'Petugas Pengambil Contoh Uji Udara BNSP',
    'Teknisi Laboratorium BNSP',
    'Penyelia Laboratorium BNSP',
    'Petugas K3 Laboratorium BNSP',
    'Manajer Mutu BNSP',
    'Manajer Teknis BNSP',
    'Kepala Laboratorium BNSP',
    'Analisis Dasar (Gravimetri & Volumetri) BNSP',
    'Analisis Spektrofotometri Serapan Atom (SSA) BNSP',
    'Analisis Spektrofotometri Uv-Vis BNSP',
    'Analisis Kromatografi Cair (HPLC) BNSP',
    'Analisis Kromatografi Gas (GC) BNSP',
    'Analisis Mikrobiologi BNSP',
    'Analisis Proksimat BNSP',
    'Welding Inspektor Standar BNSP',
    'Mengemudi Angkutan Barang Pengangkut Alat Berat BNSP',
    'Mengemudi Angkutan Barang Pengangkut Barang Khusus BNSP',
    'Mengemudi Angkutan Barang Pengangkut Peti Kemas BNSP',
    'Mengemudi Angkutan Barang Pengangkut Barang Berbahaya Dan Beracun (B3) BNSP',
    'Mengemudi Angkutan Masal Bus Gandeng Dan Tingkat BNSP',
    'Operator Scaffolding BNSP',
    'Pengawas Scaffolding BNSP',
    'Teknisi Maintenance & Repair BNSP',
    'Operator Forklift BNSP',
    'Operator Head Crane (OHC) BNSP',
    'Operator Crane Jembatan BNSP',
    'Operator Mobil Crane 35 Ton BNSP',
    'Operator Mobil Crane 70 Ton BNSP',
    'Operator Mobil Crane Diatas 70 Ton BNSP',
    'Juru Ikat Beban / Rigger BNSP',
    'Pengawas K3 Bekerja Di Ketinggian BNSP',
    'Teknisi Bekerja Di Ruang Terbatas BNSP',
    'Petugas P3K / First Aid BNSP',
    'Ahli Higine Industri Muda BNSP',
    'Petugas Fireman BNSP',
    'Teknisi K3 Bekerja Di Ketinggian BNSP',
    'Ahli K3 Bekerja Di Ketinggian BNSP',
    'Ahli Higine Industri Madya BNSP',
    'Operator K3 Industri Migas BNSP',
    'Pengawas K3 Industri Migas BNSP',
    'Operator Boiler BNSP',
    'Petugas Penanganan Bahaya H2S BNSP',
    'Authorized Gas Tester BNSP',
    'Ahli Teknik Lingkungan BNSP',
    'Pengoperasian Mesin Genset BNSP',
    'Blasting Dan Coating Operator BNSP',
    'Inspektur Coating BNSP',
    'Operator K3 Listrik BNSP',
    'Operator Welder / Juru Las BNSP',
    'Manajemen Keselamatan Kebakaran Bangunan Gedung BNSP',
    'Kepala Bagian Rekrutmen Dan Seleksi BNSP',
    'Lifting Engineer BNSP',
    'TOT LEVEL 1 BNSP',
    'TOT LEVEL 2 BNSP',
    'TOT LEVEL 3 BNSP',
    'TOT LEVEL 4 BNSP',
    'TOT LEVEL 5 BNSP',
    'TOT LEVEL 6 BNSP',
    'Perpanjangan Lisensi AK3 Kimia',
    'Perpanjangan SIO Forklift',
    'Refreshment POPAL BNSP',
    'Perpanjangan Sertifikat Ppsdm Migas',
    'Perpanjangan Lisensi P3K',
    'Perpanjangan Lisensi Ahli K3 Umum Kemnaker',
    'Perpanjangan SKP Ahli K3 Umum Kemnaker',
    'Perpanjangan SKP Dan Lisensi Ahli K3 Kimia',
    'Perpanjangan K3 Genset Kemnaker',
    'Riksa Uji Alat',
    'Perpanjangan Operator Senior Lokal Unit PLTD Kecil ESDM',
    'Perpanjangan Sertifikat Supervisor Pemeliharaan Pemanfaatan Tegangan Rendah ESDM',
    'Softskill H2S',
    'Softskill Hot Work Permit',
    'Softskill LOTO',
    'Softskill Training Sistem Manajemen Keselamatan Dan Kesehatan Kerja (SMK3) Pp No 50 Tahun 2012',
    'Softskill Manual Handling Limbah B3',
    'Softskill Training Hydrology Dan Meterology',
    'Softskill Training Iiha Connect 2025',
    'Softskill Awareness Iso 14064 For Series Green House Gas',
    'Softskill Awareness Iso 50001 For Energy Management System',
    'Softskill Certified Data Management Professional (CDMP) Foundation',
    'Softskill Human Resources Managemengt (HRM)',
    'Softskill BLS & ACLS',
    'Softskill Helikopter For Fighter & Rescue Training',
    'Softskill Water Sampling',
    'Softskill Emission Sampling',
    'Softskill Resources Estimation: Exploration Startegies, Geomodelling And Reporting',
    'Softskill Training Mine Drainage',
    'Softskill Training & Workshop Machine Learning & Data Science In Mineral Exploration',
    'Softskill Certification Lead Auditor Iso 45001: 2018',
    'Softskill Certified Maintenance & Reliability Professional (CRMP)',
    'Softskill Mining Economic And Evaluation',
    'Softskill Internal Auditor Isps Code',
    'Softskill Training Conflict Management',
    'Softskill Listrik',
    'Softskill P3K',
    'Softskill HSE',
    'Softskill Document Control & Filing System berbasis ISO 9001:2015',
    'Softskill ISO 14001:2015 SISTEM MANAJEMEN LINGKUNGAN',
    'Softskill QHSE Management System',
    'Softskill Pemahaman Perpajakan Daerah',
    'Softskill Effective Communication',
    'Softskill 5R Implementation',
    'Softskill Personal Grooming & Etiquette',
    'Softskill Awareness SMAP',
    'Softskill Training On Reading Technical Drawing In The Welding',
    'Softskill Training HR Supervisor',
    'Softskill Supply Chain Management',
    'Softskill Cost Reduction Strategy',
    'Softskill Creating Continuous Improvement Mindset',
    'Softskill Customer Service Exellence & Handling Customer Complaint',
    'Softskill Design and Troubleshooting Industrial Pneumatics',
    'Softskill Inventory Management',
    'Softskill Ms Excel',
    'Softskill Sales Forcasting and Targeting',
    'Softskill Sales Strategy Management',
    'Softskill Effective Time Management and Delegation',
    'Softskill Effective Time Management and Delagation',
    'Softskill KAIZEN',
    'Softskill Pengetahuan Dasar Boiler',
    'Softskill Effective Promotion and Advertisement Strategies',
    'Softskill Ekspor, Impor, Kepabeanan & Pelabuhan Dan Update Incoterm 2020',
    'Softskill Pelatihan Export Import',
    'Softskill Practical Import Procedure Kepabeanan, Shipping, dan Perbankan',
    'Softskill Project Management',
    'Softskill Social Media for Brand Management (Digital Marketing Fundamental)',
    'Softskill Techniques to Boost Your Creativity',
    'Softskill Smart Decision Making for Smart Person',
    'Softskill Genba Kaizen, from Simple Activity to Great Result',
    'Softskill Preventive Maintenance',
    'Softskill Motor Maintenance',
    'Softskill Bearing,Instalation,Lubrication Maintenance & Troubleshooting',
    'Softskill Electrical Protection & Troubleshooting',
    'Softskill Training Troubleshooting Inspection And Monitoring Of Machinery',
    'Softskill Effective Warehouse Management',
    'Softskill Material Safety Data Sheet ( MSDS )',
    'Softskill Pneumatic Transportation System',
    'Softskill Plumbing System & Hydrant Design',
    'Softskill Ekonomi Karbon & Perdagangan Emisi',
    'Softskill ASP.net',
    'Softskill Basic Corporate Social Responsibility',
    'Softskill Basic Human Resources',
    'Softskill Compensation and Benefit System',
    'Softskill Comprehensive Training Management System',
    'Softskill Coorporate Communication And Reputation',
    'Softskill Effective Handling of Diciplinary Actions & Terminations',
    'Softskill Hazard Analysis Critical Control Point (HACCP)',
    'Softskill Integrated Community Development Program',
    'Softskill Menyusun kamus Kompetensi',
    'Softskill Program Implementation and Reporting',
    'Softskill Return Of Investment Of Training (ROTI)',
    'Softskill Social Media For Corporate Branding',
    'Softskill HR Management',
    'Softskill Man Power Planning (MPP)',
    'Softskill Human Capital Strategy Planning',
    'Softskill Career Path Management',
    'Softskill HR Operations',
    'Softskill Compensation & Benefit',
    'Softskill Catalog Learning',
    'Softskill Pembuatan Kurikulum',
    'Softskill Corporate Culture Employee Engagement',
    'Softskill Training Design',
    'Softskill Training Evaluation',
    'Softskill Recruitment & Selection Management',
    'Softskill Worldout Analysis',
    'Softskill Hubungan Industrial',
    'Softskill Manajemen Administrasi & Pelaporaan',
    'Softskill PSAK',
    'Softskill People Development',
    'Softskill E-Learing Design & Development',
    'Softskill Return of Training Investment',
    'Softskill Konsep Employee Engagement',
    'Softskill Service Quality',
    'Softskill Basic Tax Knowledge',
    'Softskill ERP, FIRE FIGHTING & INCIDENT INVESTIGATION',
    'Softskill ERP & FIRE FIGHTING',
    'Softksill INCIDENT INVESTIGATION',
    'Reach Truck Kemnaker',
    'Softskill ISO 17025',
    'Staff Administrasi BNSP',
    'Teknisi Refrigerasi dan Teknisi Tata Udara Kemnaker',
    'Inspektur Scaffolding PPSDM',
    'Pengawas Scaffolding PPSDM',
    'Ekspor Impor Operation Staff BNSP',
    'Perpanjangan PPPU BNSP',
    'Diklat SMKP PPSDM',
    'Refreshment HIMU BNSP',
    'Supply Chain Management BNSP',
    'ACCIDENT INVESTIGATION BNSP',
    'CPOF BNSP',
    'Chain Block BNSP',
    'Teknisi AC BNSP',
    'HYAB Kemnaker',
    'Operator Boom Lift Kemnaker',
    'Vibro Standar Kemnaker',
    'Dozzer Standar Kemnaker',
    'Bomag Kemnaker',
    'Kompresor BNSP',
    'Sertifikasi Manggala Agni Level 1 BNSP',
    'TKBT Tingkat 1 BNSP',
    'TKBT Tingkat 2 BNSP',
    'Refreshment POIPPU BNSP',
    'Refreshment OPLB3 BNSP',
    'Teknisi PAA Kemnaker',
    'Draught Survey BNSP',
    'Loading Master BNSP',
    'Pengawas Instrumentasi BNSP',
    'K3 Kebakaran CB Kemnaker',
    'Operator Hoist Crane Kelas 3 Kemnaker',
    'Refreshment Inspektur Crane BNSP',
    'Inspektur Crane BNSP',
    'Teknisi K3 Ruang Terbatas Kemnaker',
    'Pengelolaan Sampah dan Limbah Non B3 BNSP',
    'Resertifikasi Pengelolaan Sampah dan Limbah Non B3 BNSP',
    'Plate Welder BNSP',
    'Pipe Welder BNSP',
    'Fillet Welder BNSP',
    'SMK3 Perusahaan Kemnaker',
    'IT Auditor BNSP',
    'Ahli K3 Listrik BNSP',
    'ICT Project Manager BNSP',
    'Auditor Lingkungan Hidup BNSP',
    'Operator Genset BNSP',
    'FNB Pengelolaan Masakan Indonesia BNSP',
    'FNB Service Pelayanan Makanan dan Minuman (Waiters) BNSP',
    'Perpanjangan Welder Plat 4G BNSP',
    'SIO Forklift Kemnaker',
    'Perpanjangan Boiler Kelas II Kemnaker',
    'Refreshment Welding BNSP',
    'Refreshment MPLB3 BNSP',
    'Operator Truck Crane Kelas 2 Kemnaker',
    'Refreshment PPPA BNSP',
    'Pengelolaan Produksi BNSP',
    'Operator PAA Kemnaker',
    'Inspektur Bejana Tekan BNSP',
    'TKPK BNSP',
    'Operator Turbin Uap Kemnaker',
    'Operator Handpallet Kemnaker',
    'Operator Manlift Kemnaker',
    'Operator Perancah BNSP',
    'Penyelia Halal BNSP',
    'Softskill Basic First Aid',
    'Softskill Basic First Aid dan Basic First Fight',
    'Supervisor Perancah BNSP',
    'Operator Genset Kelas 1 Kemnaker RI',
    'Operator Reachstacker Kemnaker',
    'PCUU BNSP',
    'Perpanjangan Sertifikat Fillet Welder BNSP',
    'Softskill 7 Habits',
    'Softskill H2S & Basic HSE',
    'Perpanjangan Lisensi K3 Listrik Kemnaker',
    'Perpanjangan Sertifikat Operator Lokal Unit PLTD Kecil ESDM',
    'Resertifikasi Petugas K3 Kesehatan BNSP',
    'Uji Riksa Forklift',
    'Softskill Basic Rigger',
    'Ahli Madya Ruang Terbatas BNSP',
    'Pelaksanaan Operasi Scaffolding BNSP',
    'Resertifikasi Inspecture Bejana Tekan BNSP',
    'Softskill FAT,H2S,BST',
    'Softskill LOTOTO dan Basic First Aid',
    'Perpanjangan Sertifikat Supervisor Pemeliharaan Pemanfaatan Tegangan Rendah ESDM',
    'Auditor Sistem Manajemen K3 BNSP',
    'Reassesment Operator Genset BNSP',
    'Operator Gondola Kemnaker',
    'Teknisi K3 Listrik BNSP',
    'Operator Lift Kemnaker RI',
    'Operator Dongkrak Mekanik Kemnaker',
    'Operator Takel Kemnaker',
    'Operator Mesin Pancang Kemnaker',
    'Pengoperasian Mesin Bubut BNSP',
    'Resertifikasi Inspektur Crane BNSP',
    'Manager Energi BNSP',
    'Perpanjangan Fillet Welder BNSP',
    'Perpanjangan MPLB3 BNSP',
    'Operator Ship Unloader Kelas 2 Kemnaker',
    'Operator Stacker Reclaimer Kemnaker',
    'Refreshment Ahli K3 Umum Kemnaker',
    'Kepala Bagian Rekrutmen & Seleksi SDM BNSP',
    'Softskill Six Sigma',
    'Perpanjangan POPAL BNSP',
    'NETWORK ADMINISTRATOR MUDA BNSP',
    'AHLI MUDA KONSTRUKSI BNSP',
    'Operator Grader Kemnaker',
    'POIPPU BNSP',
    'P3K / First Aid Kemnaker',
    'Training Safety Riding for Trainer',
    'Operator Skylift Kemnaker',
    'Lifting Supervisor BNSP',
    'Perpanjangan Lisensi Damkar A Kemnaker',
    'Perpanjangan SIO Crane',
    'Perpanjangan SIO Pesawat Uap',
    'Perpanjangan Towing Industri',
    'Perpanjangan OPLB3 BNSP',
    'Perpanjangan SIO POU',
    'Refreshment AK3U BNSP',
    'PELAKSANA K3 RUMAH SAKIT BNSP',
    'Perpanjangan AK3U Kemnaker',
    'Softskill Operator Crane Overhead Kelas 3',
    'Pelaksanaan Reklamasi BNSP',
];

    foreach ($trainings as $t) {
        MasterTraining::firstOrCreate([
            'nama_training' => $t
        ]);
    }
}
}
